{{- if eq (include "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.dbaas.install "envVar" .Values.DBAAS_ENABLED "default" true )) "true" }}
 {{template "nosql.core.secret.internal" (dict "values" . "secret" .Values.dbaas.adapter)}}
{{ end }}