---
{{- if  (.Values.backupDaemon.s3.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backupDaemon.s3.secretName }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "cassandra.defaultLabels" . | nindent 4 }}
stringData:
  username: {{ .Values.backupDaemon.s3.accessKeyId }}
  password: {{ .Values.backupDaemon.s3.accessKeySecret }}
type: Opaque
  {{ end }}

