{{- if .Values.cassandra.install }}
{{ $params := dict "isInternal" true}}
{{ $params = set $params "secret" .Values.cassandra }}
{{ $params = set $params "userEnv" .Values.INFRA_CASSANDRA_USERNAME }}
{{ $params = set $params "passEnv" .Values.INFRA_CASSANDRA_PASSWORD }}
 {{template "nosql.core.secret.fromEnv" $params}}
{{ end }}
